# Generated by Django 5.0.1 on 2025-10-06 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ime klijenta')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kompanija')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresa')),
                ('pib', models.CharField(blank=True, max_length=50, null=True, verbose_name='PIB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klijent',
                'verbose_name_plural': 'Klijenti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Mesec (1-12)')),
                ('year', models.IntegerField(verbose_name='Godina')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Broj sati')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satnica (RSD)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unos sati',
                'verbose_name_plural': 'Unosi sati',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'client', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Broj fakture')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum izdavanja')),
                ('due_date', models.DateField(verbose_name='Rok plaćanja')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('sent', 'Poslato'), ('paid', 'Plaćeno')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.timeentry')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Fakture',
                'ordering': ['-created_at'],
            },
        ),
    ]
