name: Frontend Pipeline (CI + CD)

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pipeline.yml'
  workflow_dispatch:

jobs:
  ci:
    name: Frontend CI - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kod
        uses: actions/checkout@v3

      - name: Instaliraj Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instaliraj dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build aplikaciju
        working-directory: ./frontend
        run: npm run build

      - name: Pokreni testove
        working-directory: ./frontend
        run: npm test -- --coverage --watchAll=false
        continue-on-error: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/
          retention-days: 7

  cd:
    name: Frontend CD - Deploy to S3
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout kod
        uses: actions/checkout@v3

      - name: Instaliraj Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instaliraj dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build aplikaciju
        working-directory: ./frontend
        run: npm run build
        env:
          REACT_APP_API_URL: http://${{ secrets.EC2_HOST }}/api

      - name: Deploy na S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'frontend/build'
          
